version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/PlanningPoker/planing-poker
permissions:
  - object: /opt/projectx
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file    
hooks:
  ApplicationStop:
    - location: server/scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: server/scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: server/scripts/application_start.sh
      timeout: 300
      runas: ubuntu