import { CardsDataModel } from "./types";

export const valueData: CardsDataModel[] = [
  {
    idx: 1,
    value: "0",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 2,
    value: "1",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 3,
    value: "2",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 4,
    value: "3",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 5,
    value: "5",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 6,
    value: "8",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 7,
    value: "13",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 8,
    value: "21",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 9,
    value: "34",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 10,
    value: "55",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 11,
    value: "89",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 12,
    value: "?",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
  {
    idx: 13,
    value: "Pass",
    selected: null,
    disabled: null,
    scoreTypeShort: "sp",
  },
];
